name=TTP223Row
version=1.0.4
author=Hamidreza Milaninia [ARDUnia]
maintainer=Hamidreza Milaninia [ARDUnia]
sentence=A gesture processing library for linear TTP223 capacitive touch sensors.
paragraph=This library detects complex touch patterns including multi-tap, long press, multi-finger touches, and swipe gestures (L2R, R2L, RLLR) for 2 to 5 inline TTP223 sensors using a non-blocking state machine.
category=Sensors
url=https://ardunia.ir
architectures=*
